# Generated by Django 3.2.2 on 2021-05-19 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=200)),
                ('detail', models.TextField()),
                ('enpl_area', models.CharField(max_length=200)),
                ('salary', models.IntegerField()),
                ('todo', models.CharField(max_length=200)),
                ('appl_num', models.IntegerField(default=0)),
            ],
        ),
    ]
