# Generated by Django 3.2.2 on 2021-05-19 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('albamonapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
