# Generated by Django 3.2.2 on 2021-05-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albamonapp', '0002_store_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
