# Generated by Django 3.2.2 on 2021-05-22 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albamonapp', '0003_alter_store_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.TextField(max_length=50)),
                ('content', models.TextField(max_length=200)),
                ('store_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='albamonapp.store')),
            ],
        ),
    ]
