# Generated by Django 3.2.2 on 2021-05-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albamonapp', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
