# Generated by Django 3.2.2 on 2021-05-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer', models.CharField(max_length=100)),
                ('pub_date', models.DateField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('major', models.CharField(max_length=200)),
                ('school_num', models.IntegerField()),
                ('birth', models.DateField()),
                ('favor_food', models.CharField(blank=True, default='d', max_length=200)),
                ('birth_loca', models.CharField(max_length=200)),
                ('intro', models.TextField()),
                ('mbti', models.CharField(max_length=200)),
                ('hobby', models.CharField(max_length=200)),
            ],
        ),
    ]
