# Generated by Django 3.2.2 on 2021-05-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='school_num',
            field=models.TextField(),
        ),
    ]
