# Generated by Django 3.2.2 on 2021-05-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamapp', '0003_alter_team_school_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='favor_food',
            field=models.CharField(max_length=200),
        ),
    ]
